#!/bin/bash
PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=elasticsearch
DESC="Elasticsearch Server"
DEFAULT=/src/$NAME

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
	. /etc/default/rcS
fi

ES_USER=elasticsearch
ES_GROUP=elasticsearch

JAVA_HOME="/usr/lib/jvm/java-7-openjdk"
export JAVA_HOME

# Directory where the Elasticsearch binary distribution resides
ES_HOME=/src/$NAME
MAX_OPEN_FILES=65535
LOG_DIR=$ES_HOME/logs
DATA_DIR=$ES_HOME/data
CONF_DIR=$ES_HOME/config
CONF_FILE=$CONF_DIR/elasticsearch.yml


# End of variables that can be overwritten in $DEFAULT

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
	. "$DEFAULT"
fi

# Define other required variables
PID_FILE=/var/run/$NAME.pid
DAEMON=$ES_HOME/bin/elasticsearch
DAEMON_OPTS="-Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR"

# Check DAEMON exists
test -x $DAEMON || exit 0

mkdir -p "$LOG_DIR" "$DATA_DIR" "$WORK_DIR" && chown "$ES_USER":"$ES_GROUP" "$LOG_DIR" "$DATA_DIR" "$WORK_DIR"

exec start-stop-daemon --start --user "$ES_USER" -c "$ES_USER" --exec $DAEMON -- $DAEMON_OPTS

