#!/bin/bash
ES_USER=elasticsearch
ES_GROUP=elasticsearch

JAVA_HOME="/usr/lib/jvm/java-7-openjdk"
export JAVA_HOME

ES_HOME=/src/elasticsearch
LOG_DIR=$ES_HOME/logs
DATA_DIR=$ES_HOME/data
CONF_DIR=$ES_HOME/config
CONF_FILE=$CONF_DIR/elasticsearch.yml

PID_FILE=/var/run/elasticsearch.pid
DAEMON=$ES_HOME/bin/elasticsearch
DAEMON_OPTS="-Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR"

mkdir -p "$LOG_DIR" "$DATA_DIR" "$WORK_DIR" && chown "$ES_USER":"$ES_GROUP" "$LOG_DIR" "$DATA_DIR" "$WORK_DIR"
exec start-stop-daemon --start --user "$ES_USER" -c "$ES_USER" --exec $DAEMON -- $DAEMON_OPTS